language: node_js

sudo: required

node_js:
  - "4.8.1"

services:
  - docker

before_install:
  - sudo apt-get install -y make
  - make test-image deps

before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
    chmod +x kubectl && sudo mv kubectl /usr/local/bin/

install:
  - npm install

env:
  - GROUP=sockshop COMMIT="${TRAVIS_COMMIT}" TAG="${TRAVIS_TAG}" REPO=front-end;

script:
  - make test

after_success:
  - set -e
  - if [ -z "${DOCKER_PASS}" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
  - docker login registry.cloudmule.xyz -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
  - ./scripts/build.sh
  - ./test/container.sh
  - ./scripts/push.sh

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master